[package]
name = "next-infra-connector-supabase-self-hosted"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
async-trait = { workspace = true }
next-infra-connector-api = { workspace = true }
next-infra-core = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
next-infra-connector-contract-tests = { workspace = true }
tokio = { workspace = true }
